# Generated by Django 3.0.8 on 2020-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrubric',
            name='name',
            field=models.CharField(default='SomeData', max_length=20),
        ),
    ]
